package com.fzy.weblog.web;

import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Profile;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@ComponentScan({"com.fzy.weblog.*"})
@Slf4j

class WeblogWebApplication {

	public static void main(String[] args) {
		SpringApplication.run(WeblogWebApplication.class, args);
		log.info("启动成功");
	}

}
